# Generated by Django 5.2.11 on 2026-02-24 02:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0005_teaminvitetoken_team_season'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('CREATE_TEAM', 'Create Team'), ('JOIN_TEAM', 'Join Team')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_INFO', 'Needs Info')], default='PENDING', max_length=20)),
                ('team_level', models.CharField(choices=[('HIGH_LEVEL', 'High Level'), ('MEDIUM_LEVEL', 'Medium Level'), ('LOW_LEVEL', 'Low Level')], max_length=20)),
                ('team_notes', models.TextField(blank=True)),
                ('team_name_text', models.CharField(blank=True, max_length=50)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('waiver_file', models.FileField(blank=True, upload_to='registration/waivers/')),
                ('id_file', models.FileField(blank=True, upload_to='registration/ids/')),
                ('admin_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(null=True)),
                ('rejected_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_registration_requests', to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_requests', to='leagues.division')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_registration_requests', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_requests', to='leagues.season')),
                ('team_season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_requests', to='leagues.teamseason')),
            ],
        ),
    ]
