# Generated by Django 5.2.11 on 2026-02-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='team_level',
            field=models.CharField(blank=True, choices=[('HIGH_LEVEL', 'High Level'), ('MEDIUM_LEVEL', 'Medium Level'), ('LOW_LEVEL', 'Low Level')], default='', max_length=20),
        ),
    ]
