# Generated by Django 5.2.11 on 2026-02-24 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_registrationrequest_team_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationrequest',
            name='division',
        ),
    ]
