# Generated by Django 5.2.11 on 2026-02-22 20:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CardEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card', models.CharField(choices=[('YELLOW', 'Yellow'), ('RED', 'Red')], max_length=10)),
                ('minute', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minute', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('CAPTAIN', 'Captain'), ('PLAYER', 'Player')], default='PLAYER', max_length=10)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('jersey_number', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['season', 'starts_at'], name='leagues_mat_season__cf07db_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['division', 'starts_at'], name='leagues_mat_divisio_37431d_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['venue', 'starts_at'], name='leagues_mat_venue_i_00ad93_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['home_team', 'starts_at'], name='leagues_mat_home_te_dc0559_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['away_team', 'starts_at'], name='leagues_mat_away_te_d63843_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['division', 'name'], name='leagues_tea_divisio_499691_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['is_active'], name='leagues_tea_is_acti_79ac52_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('home_team', models.F('away_team')), _negated=True), name='chk_match_home_away_different'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='leagues.match'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appearances', to='leagues.team'),
        ),
        migrations.AddField(
            model_name='cardevent',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_events', to='leagues.match'),
        ),
        migrations.AddField(
            model_name='cardevent',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_events', to='leagues.team'),
        ),
        migrations.AddField(
            model_name='goalevent',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_events', to='leagues.match'),
        ),
        migrations.AddField(
            model_name='goalevent',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goal_events', to='leagues.team'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='team_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='leagues.teamseason'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goalevent',
            name='scorer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='leagues.teammember'),
        ),
        migrations.AddField(
            model_name='cardevent',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='leagues.teammember'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appearances_as_player', to='leagues.teammember'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['team_season', 'role'], name='leagues_tea_team_se_ab74b3_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['user'], name='leagues_tea_user_id_6d0d26_idx'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('team_season', 'user'), name='uniq_teamseason_user'),
        ),
        migrations.AddIndex(
            model_name='goalevent',
            index=models.Index(fields=['match'], name='leagues_goa_match_i_dcc9d0_idx'),
        ),
        migrations.AddIndex(
            model_name='goalevent',
            index=models.Index(fields=['scorer'], name='leagues_goa_scorer__19584b_idx'),
        ),
        migrations.AddIndex(
            model_name='cardevent',
            index=models.Index(fields=['match'], name='leagues_car_match_i_deb878_idx'),
        ),
        migrations.AddIndex(
            model_name='cardevent',
            index=models.Index(fields=['player'], name='leagues_car_player__1b1d06_idx'),
        ),
        migrations.AddIndex(
            model_name='cardevent',
            index=models.Index(fields=['card'], name='leagues_car_card_26833d_idx'),
        ),
        migrations.AddIndex(
            model_name='appearance',
            index=models.Index(fields=['match', 'team'], name='leagues_app_match_i_8c5237_idx'),
        ),
        migrations.AddIndex(
            model_name='appearance',
            index=models.Index(fields=['player'], name='leagues_app_player__7c0023_idx'),
        ),
        migrations.AddConstraint(
            model_name='appearance',
            constraint=models.UniqueConstraint(fields=('match', 'player'), name='uniq_appearance_match_player'),
        ),
    ]
