# Generated by Django 5.2.11 on 2026-02-22 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_remove_teammember_uniq_teamseason_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='display_name',
        ),
    ]
