# Generated by Django 5.2.11 on 2026-02-24 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_remove_teammember_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvitetoken',
            name='team_season',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_token', to='leagues.teamseason'),
        ),
    ]
