# Generated by Django 5.2.11 on 2026-02-24 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_teaminvitetoken_team_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminvitetoken',
            name='team',
        ),
        migrations.AlterField(
            model_name='teaminvitetoken',
            name='team_season',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invite_token', to='leagues.teamseason'),
        ),
    ]
