# Generated by Django 5.2.11 on 2026-02-24 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_remove_teaminvitetoken_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='leagues.division'),
        ),
    ]
